var globalConfig = {
  srcDir: 'public/js/src',
  buildDir: 'public/js/build',
  testDir: 'public/js/tests',
  sass: {
    srcDir: 'scss'
  },
  css: {
    srcDir: 'stylesheets/development/',
    prodDir: 'public/stylesheets/release/',
    src: '',
    dest: ''
  },
  js: {
    srcFile: '',
    buildFile: '',
    minifiedFile: '',
    testFile: ''
  }
};

module.exports = function (grunt) {
  'use strict';

  grunt.initConfig({
    pkg: grunt.file.readJSON('package.json'),
    globalConfig: globalConfig,

    jshint: {
      files: [
        'Gruntfile.js'
      ],
    },

    watch: {
      compass: {
        files: [globalConfig.sass.srcDir + '/**/*.scss'],
        tasks: ['compass:development']
      }
    },
    cssmin: {
      singleFile: {
        files: {
          '<%= globalConfig.css.dest %>': '<%= globalConfig.css.src %>'
        }
      }
    },
    compass: {
      development: {
        options: {
          config: 'config.rb'
        },
        files: [{
          expand: true,
          cwd: globalConfig.sass.srcDir + '/',
          src: ['**/*.scss'],
          dest: globalConfig.css.prodDir,
          ext: '.css'
        }]
      }
    }
  });

  // Load all npm tasks using matchdep
  require('matchdep').filterDev('grunt-*').forEach(grunt.loadNpmTasks);

  var browserifyPagesRE = new RegExp(globalConfig.srcDir + '\/pages\/');
  var jsTestFileRE = new RegExp(globalConfig.testDir);

  /*
   * On the watch event, we check to see if we are changing a browserify js
   * file. If so, we update the globalConfig object which is what the
   * browserify and uglify tasks are using to build their respective files.
   */
  grunt.event.on('watch', function (action, filepath, target) {
    if ((action === 'changed' || action === 'added') &&
      (browserifyPagesRE.test(filepath) ||
        jsTestFileRE.test(filepath))) {

      globalConfig.js.srcFile = filepath;
      globalConfig.js.buildFile = filepath.replace('/src/', '/build/');
      globalConfig.js.minifiedFile = globalConfig.js.buildFile.replace('.js', '.min.js');
    }
  });

  /*
   * This task is called from the command line when a page-specific CSS file is
   * generated by Compass so we can have minified version of the compiled file.
   */
  grunt.registerTask('compass:minify', function () {
    var filepath = grunt.option('file');

    globalConfig.css.src = filepath;
    globalConfig.css.dest = filepath.replace('.css', '.min.css').replace(globalConfig.css.srcDir, globalConfig.css.prodDir);

    grunt.task.run('cssmin:singleFile');
  });

  grunt.loadNpmTasks('grunt-contrib-jshint');
  grunt.registerTask('default', ['jshint']);
};
